plugins {
    id 'java'
    id 'application'
    id 'distribution'
}

group = 'com.sandbox'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    awsSdkVersion = "latest.release"
    awsKplVersion = "latest.release"
}

dependencies {
    implementation "software.amazon.awssdk:s3:$awsSdkVersion"
    implementation "software.amazon.awssdk:iam:$awsSdkVersion"
    implementation "software.amazon.awssdk:sts:$awsSdkVersion"
    implementation "software.amazon.awssdk:kinesis:$awsSdkVersion"

    implementation "com.amazonaws:amazon-kinesis-producer:$awsKplVersion"
    implementation "software.amazon.kinesis:amazon-kinesis-client:3.1.2"

    implementation("info.picocli:picocli:4.7.7")
}

application {
    mainClass = 'AwsSdkSandbox'
}


jar {
    archiveFileName = "${project.name}.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes("Implementation-Title": project.name)
        attributes("Built-At": new Date().format("yyyy-MM-dd HH:mm z"))
        attributes("Main-Class": "com.sandbox.AwsSdkSandbox")
        attributes 'Implementation-Version': "${project.version}"
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
}

distributions {
    main {
        contents {
            from jar
            into "/"
        }
    }
}