plugins {
    id 'java'
    id 'application'
}

group = 'com.sandbox'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    awsSdkVersion = "latest.release"
}

dependencies {
    implementation "software.amazon.awssdk:s3:$awsSdkVersion"
    implementation "software.amazon.awssdk:iam:$awsSdkVersion"
    implementation "software.amazon.awssdk:sts:$awsSdkVersion"
    implementation "software.amazon.awssdk:kinesis:$awsSdkVersion"

    implementation("info.picocli:picocli:4.7.7")
}

application {
    mainClass = 'AwsUserS3Manager'
}